### ISSUE TITLE
Немного моего занудства

### ISSUE THREAD

**Issue by Evil-Spirit** [AlexGyver/3dpov#1]
Привет! Крутые проекты!
Есть одна штука по работе с таймерами:

https://github.com/AlexGyver/3dpov/blob/b275607f90fed44ef55b7f1cc5420258c8421597/firmware/3Dpov/3Dpov.ino#L33
```
#define EVERY_MS(x) \
  static uint32_t tmr;\
  bool flag = millis() - tmr >= (x);\
  if (flag) tmr += (x);\
  if (flag)
```

Если ты поймешь эту концепцию, то твои таймеры никогда не будут 'утекать'.
Я таким образом делал часы. Они работают стабильно месяцами. Для точности можно еще micros() использовать.

**Comment by AlexGyver** [comment]
Привет, это то да, но такая конструкция не переживет переполнение и пропуск одного периода. Я вот тут https://alexgyver.ru/lessons/time/
 писал по временнЫм конструкциям

**Comment by Evil-Spirit** [comment]
На самом деле, переживает она переполнение.
И чтобы это произошло, условие делается вот так:
https://github.com/Evil-Spirit/EvilClock/blob/d177238ec19e71305026a837fc0c2c9ddfdbe57f/source/led_music/Clock.h#L19
Эти часы живут на стене уже много лет без сбоев, несмотря на то, что mircos() переполняется довольно-таки часто.

**Comment by AlexGyver** [comment]
Странно, я тестировал, таймер переставал работать. Возможно при каких то условиях так оно и есть, надо поковыряться

**Comment by AlexGyver** [comment]
Всё верно. Простая конструкция работает корректно, а вот если нагородить защиту от пропуска периода - то переполнение алгоритм уже не переживет и нужна дополнительная проверка. Без защиты от пропуска периодов конструкция работает, тогда чутка дополню урок, спасибо)
